// <auto-generated />
using DataAccess.NetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.NetCore.Migrations
{
    [DbContext(typeof(ApplicationBEDbContext))]
    [Migration("20250419060052_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.NetCore.DO.HB_Rooms", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"), 1L, 1);

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomSquare")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomID = -1,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala01",
                            RoomSquare = 1
                        },
                        new
                        {
                            RoomID = -2,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala02",
                            RoomSquare = 1
                        },
                        new
                        {
                            RoomID = -3,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala03",
                            RoomSquare = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
