// <auto-generated />
using System;
using DataAccess.NetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.NetCore.Migrations
{
    [DbContext(typeof(ApplicationBEDbContext))]
    [Migration("20250513013411_initHotel")]
    partial class initHotel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.NetCore.DO.HB_Hotels", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelID");

                    b.ToTable("HB_Hotels");

                    b.HasData(
                        new
                        {
                            HotelID = -1,
                            CreatedDate = new DateTime(2025, 5, 13, 8, 34, 11, 110, DateTimeKind.Local).AddTicks(1699),
                            Description = "Hotel 1",
                            HotelName = "Hotel 1"
                        },
                        new
                        {
                            HotelID = -2,
                            CreatedDate = new DateTime(2025, 5, 13, 8, 34, 11, 110, DateTimeKind.Local).AddTicks(1710),
                            Description = "Hotel 2",
                            HotelName = "Hotel 2"
                        },
                        new
                        {
                            HotelID = -3,
                            CreatedDate = new DateTime(2025, 5, 13, 8, 34, 11, 110, DateTimeKind.Local).AddTicks(1712),
                            Description = "Hotel 3",
                            HotelName = "Hotel 3"
                        });
                });

            modelBuilder.Entity("DataAccess.NetCore.DO.HB_Rooms", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"), 1L, 1);

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomSquare")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.ToTable("HB_Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = -1,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala01",
                            RoomSquare = 1
                        },
                        new
                        {
                            RoomID = -2,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala02",
                            RoomSquare = 1
                        },
                        new
                        {
                            RoomID = -3,
                            HotelID = 0,
                            IsActive = 0,
                            RoomNumber = "lalala03",
                            RoomSquare = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
